server:
  port : 9080
spring:
  application:
    name: product-microservice
  datasource:
    url: jdbc:h2:mem:customerdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console